version: '3.1'
services:
# Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - .config/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    networks:
      prometheus-network:
 
# Grafana
  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "0" #[ Execute  id -u in terminal to find the user id from where you are invoking docker compose]
    volumes:
      - /opt/grafana_db:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    networks:
      prometheus-network:
 
#Push Gateway
  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      prometheus-network:
    labels:
      org.label-schema.group: "monitoring"
 
 
# Network Configuration
networks:
  prometheus-network:
    driver: bridge
    name: prometheus-network